from app.models.models import (
    AiCallUsage,
    Appointment,
    BlacklistNumber,
    CallLog,
    Campaign,
    CampaignNumber,
    Extension,
    InboundRoute,
    OutboundRoute,
    PriorityNumber,
    Queue,
    SystemErrorLog,
    SystemSettings,
    TimeCondition,
    TimeGroup,
    Trunk,
    User,
    VoiceBot,
)

__all__ = [
    "AiCallUsage",
    "Appointment",
    "BlacklistNumber",
    "CallLog",
    "Campaign",
    "CampaignNumber",
    "Extension",
    "InboundRoute",
    "OutboundRoute",
    "PriorityNumber",
    "Queue",
    "SystemErrorLog",
    "SystemSettings",
    "TimeCondition",
    "TimeGroup",
    "Trunk",
    "User",
    "VoiceBot",
]

